# Generated by Django 4.0.6 on 2022-08-08 14:02

import app_data.filechecker
import app_data.models
import app_data.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exiffield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('message_date', models.DateField()),
                ('message', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', app_data.filechecker.ContentTypeRestrictedFileField(upload_to=app_data.models.user_directory_path, validators=[app_data.validators.validate_file_extension])),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('exif', exiffield.fields.ExifField(default={}, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_file', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
