# Generated by Django 4.0.6 on 2022-08-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='fileupload',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
