# Generated by Django 4.0.6 on 2022-08-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0002_alter_fileupload_options_fileupload_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='name',
            new_name='file_name',
        ),
    ]
