# Generated by Django 4.0.6 on 2022-08-09 20:53

import app_data.filechecker
import app_data.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0003_rename_name_fileupload_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=app_data.filechecker.ContentTypeRestrictedFileField(upload_to=app_data.models.user_directory_path),
        ),
    ]
