# Generated by Django 4.0.6 on 2022-08-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0004_alter_fileupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='file_type',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True),
        ),
    ]
