# Generated by Django 4.0.6 on 2022-08-11 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0005_fileupload_file_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
