# Generated by Django 4.0.6 on 2022-08-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_alter_user_managers_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='Picture'),
        ),
    ]
