# Generated by Django 4.0.6 on 2022-08-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_info',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.URLField(blank=True, max_length=80, null=True),
        ),
    ]
